#ifndef __TOKEN_H
#define __TOKEN_H

#include <inttypes.h>

typedef uint8_t tag_t;
enum tag_enum {
  TAG_EOF = 0,
  TAG_EOL,
  TAG_COMMENT,
  TAG_IDENT,
  TAG_TYPE_NAME,
  TAG_ASSIGN,
  TAG_INVARIABLE,
  TAG_VARIABLE,
  TAG_DEL,
  TAG_GC,
  TAG_MEM,
  TAG_LPAREN,
  TAG_RPAREN,
  TAG_COMMA,
  TAG_COLON,
  TAG_PLUS,
  TAG_MINUS,
  TAG_TIMES,
  TAG_DIVIDE,
  TAG_MOD,
  TAG_AND,
  TAG_OR,
  TAG_NOT,
  TAG_BITWISE_SHL,
  TAG_BITWISE_SHR,
  TAG_BITWISE_AND,
  TAG_BITWISE_OR,
  TAG_BITWISE_XOR,
  TAG_BITWISE_NOT,
  TAG_BIN,
  TAG_HEX,
  TAG_INT,
  TAG_FLOAT,
  TAG_BYTE,
  TAG_STRING,
  TAG_TRUE,
  TAG_FALSE,
  TAG_NIL,
  TAG_LIST,
  TAG_DICT,
  TAG_OF,
  TAG_ARR_DECL,
  TAG_TYPE_INT,
  TAG_TYPE_FLOAT,
  TAG_TYPE_BYTE,
  TAG_TYPE_STRING,
  TAG_TYPE_BOOLEAN,
  TAG_AS,
  TAG_IS,
  TAG_TYPEOF,
  TAG_RANGE,
  TAG_LBRACKET,
  TAG_RBRACKET,
  TAG_IF,
  TAG_THEN,
  TAG_ELSE,
  TAG_DO,
  TAG_WHILE,
  TAG_FOR,
  TAG_IN,
  TAG_BREAK,
  TAG_CONTINUE,
  TAG_MATCH,
  TAG_STEP,
  TAG_GT,
  TAG_LT,
  TAG_GE,
  TAG_LE,
  TAG_EQ,
  TAG_NE,
  TAG_DUMP,
  TAG_PRINT,
  TAG_INPUT,
  TAG_READ,
  TAG_TO_HEX,
  TAG_TO_BIN,
  TAG_BEGIN,
  TAG_END,
  TAG_MEMBER_ACCESS,
  TAG_FIELD_NAME,
  TAG_METHOD_CALL,
  TAG_FUNC_DEF,
  TAG_FUNC_RETURN,
  TAG_RAND,
  TAG_RANDOM_CHOICE,
  TAG_ABS,
  TAG_SIN,
  TAG_COS,
  TAG_TAN,
  TAG_SQRT,
  TAG_EXP,
  TAG_LN,
  TAG_LOG,
};

static const char* tag_names[] = {
  "EOF",
  "EOL",
  "COMMENT",
  "IDENT",
  "TYPE-NAME",
  "ASSIGN",
  "INVARIABLE",
  "VARIABLE",
  "DELETE",
  "GC",
  "MEM",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "COLON",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "BITWISE_SHL",
  "BITWISE_SHR",
  "BITWISE_AND",
  "BITWISE_OR",
  "BITWISE_XOR",
  "BITWISE_NOT",
  "BIN",
  "HEX",
  "INT",
  "FLOAT",
  "BYTE",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "LIST",
  "DICT",
  "OF",
  "ARRAY-DECL",
  "INT-TYPE",
  "FLOAT-TYPE",
  "BYTE-TYPE",
  "STRING-TYPE",
  "BOOLEAN-TYPE",
  "AS",
  "IS",
  "TYPE-OF",
  "RANGE-TO",
  "OPEN_SUBSCRIPT_BRACKET",
  "CLOSE_SUBSCRIPT_BRACKET",
  "IF",
  "THEN",
  "ELSE",
  "DO",
  "WHILE",
  "FOR",
  "IN",
  "BREAK",
  "CONTINUE",
  "MATCH",
  "STEP",
  "GT",
  "LT",
  "GE",
  "LE",
  "EQ",
  "NE",
  "DUMP",
  "PRINT",
  "INPUT",
  "READ-FILE",
  "TO-HEX",
  "TO-BIN",
  "BEGIN",
  "END",
  "MEMBER-ACCESS",
  "FIELD-NAME",
  "METHOD-CALL",
  "FUNCTION-DEFINITION",
  "FUNCTION-RETURN",
  "RAND",
  "RANDOM-CHOICE",
  "ABS",
  "SIN",
  "COS",
  "TAN",
  "SQR",
  "EXP",
  "LN",
  "LOG",
};

typedef struct {
  tag_t tag;
  union {
    int32_t intval;
    float floatval;
    char* string;
    char ch;
  } ;
} token_t;

static const token_t reserved[] = {
  { TAG_FUNC_DEF,      .string = (char *) "fn" },
  { TAG_FUNC_RETURN,   .string = (char *) "return" },
  { TAG_IF,            .string = (char *) "if" },
  { TAG_THEN,          .string = (char *) "then" },
  { TAG_ELSE,          .string = (char *) "else" },
  { TAG_AND,           .string = (char *) "and" },
  { TAG_OR,            .string = (char *) "or" },
  { TAG_NOT,           .string = (char *) "not" },
  { TAG_INVARIABLE,    .string = (char *) "val" },
  { TAG_VARIABLE,      .string = (char *) "var" },
  { TAG_DEL,           .string = (char *) "del" },
  { TAG_GC,            .string = (char *) "gc" },
  { TAG_MEM,           .string = (char *) "mem" },
  { TAG_DUMP,          .string = (char *) "dump" },
  { TAG_PRINT,         .string = (char *) "print" },
  { TAG_INPUT,         .string = (char *) "input" },
  { TAG_READ,          .string = (char *) "read" },
  { TAG_TO_HEX,        .string = (char *) "hex" },
  { TAG_TO_BIN,        .string = (char *) "bin" },
  { TAG_DO,            .string = (char *) "do" },
  { TAG_WHILE,         .string = (char *) "while" },
  { TAG_FOR,           .string = (char *) "for" },
  { TAG_IN,            .string = (char *) "in" },
  { TAG_BREAK,         .string = (char *) "break"},
  { TAG_CONTINUE,      .string = (char *) "continue"},
  { TAG_MATCH,         .string = (char *) "match" },
  { TAG_STEP,          .string = (char *) "step" },
  { TAG_NIL,           .string = (char *) "nil" },
  { TAG_LIST,          .string = (char *) "list" },
  { TAG_DICT,          .string = (char *) "dict" },
  { TAG_ARR_DECL,      .string = (char *) "arr" },
  { TAG_TYPE_INT,      .string = (char *) "int" },
  { TAG_TYPE_FLOAT,    .string = (char *) "float" },
  { TAG_TYPE_BYTE,     .string = (char *) "byte" },
  { TAG_TYPE_STRING,   .string = (char *) "string" },
  { TAG_TYPE_BOOLEAN,  .string = (char *) "boolean" },
  { TAG_AS,            .string = (char *) "as" },
  { TAG_IS,            .string = (char *) "is" },
  { TAG_TYPEOF,        .string = (char *) "type" },
  { TAG_TRUE,          .string = (char *) "true" },
  { TAG_FALSE,         .string = (char *) "false" },
  { TAG_RAND,          .string = (char *) "rand" },
  { TAG_ABS,           .string = (char *) "abs" },
  { TAG_SIN,           .string = (char *) "sin" },
  { TAG_COS,           .string = (char *) "cos" },
  { TAG_TAN,           .string = (char *) "tan" },
  { TAG_SQRT,          .string = (char *) "sqrt" },
  { TAG_EXP,           .string = (char *) "exp" },
  { TAG_LN,            .string = (char *) "ln" },
  { TAG_LOG,           .string = (char *) "log" },
};

#endif

