#pragma once

#include <inttypes.h>

typedef uint8_t tag_t;

enum tag_enum {
    TAG_ERROR,
    TAG_EOF,
    TAG_EOL,
    TAG_INDENT,
    TAG_IDENT,
    TAG_ASSIGN,
    TAG_INVARIABLE,
    TAG_VARIABLE,
    TAG_DEL,
    TAG_GC,
    TAG_MEM,
    TAG_ENV,
    TAG_LPAREN,
    TAG_RPAREN,
    TAG_COMMA,
    TAG_MAPS_TO,
    TAG_COLON,
    TAG_PLUS,
    TAG_MINUS,
    TAG_TIMES,
    TAG_DIVIDE,
    TAG_MOD,
    TAG_AND,
    TAG_OR,
    TAG_NOT,
    TAG_BITWISE_SHL,
    TAG_BITWISE_SHR,
    TAG_BITWISE_AND,
    TAG_BITWISE_OR,
    TAG_BITWISE_XOR,
    TAG_BITWISE_NOT,
    TAG_BIN,
    TAG_HEX,
    TAG_INT,
    TAG_FLOAT,
    TAG_BYTE,
    TAG_CHAR,
    TAG_STRING,
    TAG_TRUE,
    TAG_FALSE,
    TAG_NIL,
    TAG_LIST,
    TAG_DICT,
    TAG_ARR_DECL,
    TAG_TYPE,
    TAG_TYPE_INT,
    TAG_TYPE_FLOAT,
    TAG_TYPE_BYTE,
    TAG_TYPE_BYTEARRAY,
    TAG_TYPE_STRING,
    TAG_TYPE_BOOLEAN,
    TAG_TYPE_LIST,
    TAG_TYPE_MAP,
    TAG_TYPEDEF_STRUCT,
    TAG_AS,
    TAG_IS,
    TAG_TYPEDEF,
    TAG_TYPEOF,
    TAG_DATA,
    TAG_RANGE,
    TAG_LBRACKET,
    TAG_RBRACKET,
    TAG_IF,
    TAG_THEN,
    TAG_ELSE,
    TAG_DO,
    TAG_WHILE,
    TAG_FOR,
    TAG_IN,
    TAG_BREAK,
    TAG_CONTINUE,
    TAG_MATCH,
    TAG_STEP,
    TAG_GT,
    TAG_LT,
    TAG_GE,
    TAG_LE,
    TAG_EQ,
    TAG_NE,
    TAG_DUMP,
    TAG_PRINT,
    TAG_INPUT,
    TAG_READ,
    TAG_TO_HEX,
    TAG_TO_BIN,
    TAG_BEGIN,
    TAG_END,
    TAG_MEMBER_ACCESS,
    TAG_FIELD_ACCESS,
    TAG_METHOD_CALL,
    TAG_FUNC_DEF,
    TAG_FUNC_RETURN,
    TAG_RAND,
    TAG_ABS,
    TAG_SIN,
    TAG_COS,
    TAG_TAN,
    TAG_SQRT,
    TAG_EXP,
    TAG_LN,
    TAG_LOG,
};

typedef struct {
    tag_t tag;
    uint8_t err;
    uint8_t indent;
    const char *start;
    uint32_t len;
} token_t;
