#pragma once

#include <inttypes.h>

typedef uint8_t tag_t;

enum tag_enum {
    TAG_ERROR,
    TAG_EOF,
    TAG_EOL,
    TAG_IDENT,
    TAG_ASSIGN,
    TAG_INVARIABLE,
    TAG_VARIABLE,
    TAG_DEL,
    TAG_GC,
    TAG_MEM,
    TAG_ENV,
    TAG_LPAREN,
    TAG_RPAREN,
    TAG_COMMA,
    TAG_MAPS_TO,
    TAG_COLON,
    TAG_PLUS,
    TAG_MINUS,
    TAG_TIMES,
    TAG_DIVIDE,
    TAG_MOD,
    TAG_AND,
    TAG_OR,
    TAG_NOT,
    TAG_BITWISE_SHL,
    TAG_BITWISE_SHR,
    TAG_BITWISE_AND,
    TAG_BITWISE_OR,
    TAG_BITWISE_XOR,
    TAG_BITWISE_NOT,
    TAG_BIN,
    TAG_HEX,
    TAG_INT,
    TAG_FLOAT,
    TAG_BYTE,
    TAG_CHAR,
    TAG_STRING,
    TAG_TRUE,
    TAG_FALSE,
    TAG_NIL,
    TAG_LIST,
    TAG_DICT,
    TAG_ARR_DECL,
    TAG_TYPE,
    TAG_TYPE_INT,
    TAG_TYPE_FLOAT,
    TAG_TYPE_BYTE,
    TAG_TYPE_BYTEARRAY,
    TAG_TYPE_STRING,
    TAG_TYPE_BOOLEAN,
    TAG_TYPE_LIST,
    TAG_TYPE_MAP,
    TAG_TYPEDEF_STRUCT,
    TAG_AS,
    TAG_IS,
    TAG_TYPEDEF,
    TAG_TYPEOF,
    TAG_DATA,
    TAG_RANGE,
    TAG_LBRACKET,
    TAG_RBRACKET,
    TAG_IF,
    TAG_THEN,
    TAG_ELSE,
    TAG_DO,
    TAG_WHILE,
    TAG_FOR,
    TAG_IN,
    TAG_BREAK,
    TAG_CONTINUE,
    TAG_MATCH,
    TAG_STEP,
    TAG_GT,
    TAG_LT,
    TAG_GE,
    TAG_LE,
    TAG_EQ,
    TAG_NE,
    TAG_DUMP,
    TAG_PRINT,
    TAG_INPUT,
    TAG_READ,
    TAG_TO_HEX,
    TAG_TO_BIN,
    TAG_BEGIN,
    TAG_END,
    TAG_MEMBER_ACCESS,
    TAG_FIELD_ACCESS,
    TAG_METHOD_CALL,
    TAG_FUNC_DEF,
    TAG_FUNC_RETURN,
    TAG_RAND,
    TAG_ABS,
    TAG_SIN,
    TAG_COS,
    TAG_TAN,
    TAG_SQRT,
    TAG_EXP,
    TAG_LN,
    TAG_LOG,
};

static const char *tag_names[] = {
    [TAG_ERROR] = "ERROR",
    [TAG_EOF] = "EOF",
    [TAG_EOL] = "EOL",
    [TAG_IDENT] = "IDENT",
    [TAG_ASSIGN] = "ASSIGN",
    [TAG_INVARIABLE] = "INVARIABLE",
    [TAG_VARIABLE] = "VARIABLE",
    [TAG_DEL] = "DEL",
    [TAG_GC] = "GC",
    [TAG_MEM] = "MEM",
    [TAG_ENV] = "ENV",
    [TAG_LPAREN] = "LPAREN",
    [TAG_RPAREN] = "RPAREN",
    [TAG_COMMA] = "COMMA",
    [TAG_MAPS_TO] = "MAPS_TO",
    [TAG_COLON] = "COLON",
    [TAG_PLUS] = "PLUS",
    [TAG_MINUS] = "MINUS",
    [TAG_TIMES] = "TIMES",
    [TAG_DIVIDE] = "DIVIDE",
    [TAG_MOD] = "MOD",
    [TAG_AND] = "LOGICAL AND",
    [TAG_OR] = "LOGICAL OR",
    [TAG_NOT] = "LOGICAL NOT",
    [TAG_BITWISE_SHL] = "SHL",
    [TAG_BITWISE_SHR] = "SHR",
    [TAG_BITWISE_AND] = "AND",
    [TAG_BITWISE_OR] = "OR",
    [TAG_BITWISE_XOR] = "XOR",
    [TAG_BITWISE_NOT] = "NOT",
    [TAG_BIN] = "BIN",
    [TAG_HEX] = "HEX",
    [TAG_INT] = "INT",
    [TAG_FLOAT] = "FLOAT",
    [TAG_BYTE] = "BYTE",
    [TAG_CHAR] = "CHAR",
    [TAG_STRING] = "STRING",
    [TAG_TRUE] = "TRUE",
    [TAG_FALSE] = "FALSE",
    [TAG_NIL] = "NIL",
    [TAG_LIST] = "LIST",
    [TAG_DICT] = "DICT",
    [TAG_ARR_DECL] = "ARR_DECL",
    [TAG_TYPE] = "TYPE",
    [TAG_TYPE_INT] = "TYPE INT",
    [TAG_TYPE_FLOAT] = "TYPE FLOAT",
    [TAG_TYPE_BYTE] = "TYPE BYTE",
    [TAG_TYPE_BYTEARRAY] = "TYPE BYTEARRAY",
    [TAG_TYPE_STRING] = "TYPE STRING",
    [TAG_TYPE_BOOLEAN] = "TYPE BOOLEAN",
    [TAG_TYPE_LIST] = "TYPE LIST",
    [TAG_TYPE_MAP] = "TYPE MAP",
    [TAG_TYPEDEF_STRUCT] = "TYPEDEF STRUCT",
    [TAG_AS] = "AS",
    [TAG_IS] = "IS",
    [TAG_TYPEDEF] = "TYPEDEF",
    [TAG_TYPEOF] = "TYPEOF",
    [TAG_DATA] = "DATA",
    [TAG_RANGE] = "RANGE",
    [TAG_LBRACKET] = "LBRACKET",
    [TAG_RBRACKET] = "RBRACKET",
    [TAG_IF] = "IF",
    [TAG_THEN] = "THEN",
    [TAG_ELSE] = "ELSE",
    [TAG_DO] = "DO",
    [TAG_WHILE] = "WHILE",
    [TAG_FOR] = "FOR",
    [TAG_IN] = "IN",
    [TAG_BREAK] = "BREAK",
    [TAG_CONTINUE] = "CONTINUE",
    [TAG_MATCH] = "MATCH",
    [TAG_STEP] = "STEP",
    [TAG_GT] = "GT",
    [TAG_LT] = "LT",
    [TAG_GE] = "GE",
    [TAG_LE] = "LE",
    [TAG_EQ] = "EQ",
    [TAG_NE] = "NE",
    [TAG_DUMP] = "DUMP",
    [TAG_PRINT] = "PRINT",
    [TAG_INPUT] = "INPUT",
    [TAG_READ] = "READ",
    [TAG_TO_HEX] = "TO_HEX",
    [TAG_TO_BIN] = "TO_BIN",
    [TAG_BEGIN] = "BEGIN",
    [TAG_END] = "END",
    [TAG_MEMBER_ACCESS] = "MEMBER ACCESS",
    [TAG_FIELD_ACCESS] = "FIELD ACCESS",
    [TAG_METHOD_CALL] = "METHOD CALL",
    [TAG_FUNC_DEF] = "FUNC DEF",
    [TAG_FUNC_RETURN] = "FUNC RETURN",
    [TAG_RAND] = "RAND",
    [TAG_ABS] = "ABS",
    [TAG_SIN] = "SIN",
    [TAG_COS] = "COS",
    [TAG_TAN] = "TAN",
    [TAG_SQRT] = "SQRT",
    [TAG_EXP] = "EXP",
    [TAG_LN] = "LN",
    [TAG_LOG] = "LOG",
};

typedef struct {
    tag_t tag;
    uint8_t err;
    const char *start;
    uint32_t len;
} token_t;
