#pragma once

typedef enum {
    VM_OP_NO_SUCH_OP,
    VM_OP_NOP,
    VM_OP_PUSHI,
    VM_OP_LOADI,
    VM_OP_LOADI_1N,
    VM_OP_LOADI_0,
    VM_OP_LOADI_1,
    VM_OP_LOADS,
    VM_OP_NEGATE,
    VM_OP_ADD,
    VM_OP_SUB,
    VM_OP_MUL,
    VM_OP_DIV,
    VM_OP_REM,
    VM_OP_BIN_OR,
    VM_OP_BIN_XOR,
    VM_OP_BIN_AND,
    VM_OP_BIN_SHL,
    VM_OP_BIN_SHR,
    VM_OP_INC,
    VM_OP_DEC,
    VM_OP_ASSIGN,
    VM_OP_RET,
    VM_OP_MAX,
} vm_op_t;

static const char *op_names[VM_OP_MAX] = {
    [VM_OP_NO_SUCH_OP] = "ERROR_NO_SUCH_OP",
    [VM_OP_NOP] = "NOP",
    [VM_OP_PUSHI] = "PUSHI",
    [VM_OP_LOADI] = "LOADI",
    [VM_OP_LOADI_1N] = "LOADI IMM [-1]",
    [VM_OP_LOADI_0] = "LOADI IMM [0]",
    [VM_OP_LOADI_1] = "LOADI IMM [1]",
    [VM_OP_LOADS] = "LOADS",
    [VM_OP_NEGATE] = "NEGATE",
    [VM_OP_ADD] = "ADD",
    [VM_OP_SUB] = "SUB",
    [VM_OP_MUL] = "MUL",
    [VM_OP_DIV] = "DIV",
    [VM_OP_REM] = "REM",
    [VM_OP_BIN_OR] = "OR",
    [VM_OP_BIN_XOR] = "XOR",
    [VM_OP_BIN_AND] = "AND",
    [VM_OP_BIN_SHL] = "SHL",
    [VM_OP_BIN_SHR] = "SHR",
    [VM_OP_INC] = "INC",
    [VM_OP_DEC] = "DEC",
    [VM_OP_ASSIGN] = "ASSIGN",
    [VM_OP_RET] = "RET",
};
