#pragma once

typedef enum {
    VM_OP_NO_SUCH_OP,
    VM_OP_ICONST,
    VM_OP_SCONST,
    VM_OP_ACONST,
    VM_OP_BPUSH,
    VM_OP_IPUSH,
    VM_OP_IPUSH_1N,
    VM_OP_IPUSH_0,
    VM_OP_IPUSH_1,
    VM_OP_ZPUSH_F,
    VM_OP_ZPUSH_T,
    VM_OP_AALLOC,
    VM_OP_ALOAD,
    VM_OP_LOGICAL_AND,
    VM_OP_LOGICAL_OR,
    VM_OP_LOGICAL_NOT,
    VM_OP_GT,
    VM_OP_LT,
    VM_OP_GE,
    VM_OP_LE,
    VM_OP_EQ,
    VM_OP_NE,
    VM_OP_NIL,
    VM_OP_NEG,
    VM_OP_ADD,
    VM_OP_SUB,
    VM_OP_MUL,
    VM_OP_DIV,
    VM_OP_REM,
    VM_OP_BIN_OR,
    VM_OP_BIN_XOR,
    VM_OP_BIN_AND,
    VM_OP_BIN_SHL,
    VM_OP_BIN_SHR,
    VM_OP_INC,
    VM_OP_DEC,
    VM_OP_ASSIGN,
    VM_OP_JEQ,
    VM_OP_JZ,
    VM_OP_JMP,
    VM_OP_PRINT,
    VM_OP_RET,
    VM_OP_NOP,
    VM_OP_MAX,
} vm_op_t;

static const char *op_names[VM_OP_MAX] = {
    [VM_OP_NO_SUCH_OP] = "ERROR_NO_SUCH_OP",
    [VM_OP_ICONST] = "ICONST",
    [VM_OP_SCONST] = "SCONST",
    [VM_OP_ACONST] = "ACONST",
    [VM_OP_BPUSH] = "BPUSH",
    [VM_OP_IPUSH] = "IPUSH",
    [VM_OP_IPUSH_1N] = "IPUSH IMM [-1]",
    [VM_OP_IPUSH_0] = "IPUSH IMM [0]",
    [VM_OP_IPUSH_1] = "IPUSH IMM [1]",
    [VM_OP_ZPUSH_F] = "ZPUSH IMM [F]",
    [VM_OP_ZPUSH_T] = "ZPUSH IMM [T]",
    [VM_OP_AALLOC] = "AALLOC",
    [VM_OP_ALOAD] = "ALOAD",
    [VM_OP_LOGICAL_AND] = "ZAND",
    [VM_OP_LOGICAL_OR] = "ZOR",
    [VM_OP_LOGICAL_NOT] = "ZNOT",
    [VM_OP_GT] = "GT",
    [VM_OP_LT] = "LT",
    [VM_OP_GE] = "GE",
    [VM_OP_LE] = "LE",
    [VM_OP_EQ] = "EQ",
    [VM_OP_NE] = "NE",
    [VM_OP_NIL] = "NIL",
    [VM_OP_NEG] = "NEG",
    [VM_OP_ADD] = "ADD",
    [VM_OP_SUB] = "SUB",
    [VM_OP_MUL] = "MUL",
    [VM_OP_DIV] = "DIV",
    [VM_OP_REM] = "REM",
    [VM_OP_BIN_OR] = "OR",
    [VM_OP_BIN_XOR] = "XOR",
    [VM_OP_BIN_AND] = "AND",
    [VM_OP_BIN_SHL] = "SHL",
    [VM_OP_BIN_SHR] = "SHR",
    [VM_OP_INC] = "INC",
    [VM_OP_DEC] = "DEC",
    [VM_OP_ASSIGN] = "ASSIGN",
    [VM_OP_JEQ] = "JEQ",
    [VM_OP_JZ] = "JZ",
    [VM_OP_JMP] = "JMP",
    [VM_OP_PRINT] = "PRINT",
    [VM_OP_RET] = "RET",
    [VM_OP_NOP] = "NOP",
};
